import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Play, Video, Search, Share2, ChevronLeft, ChevronRight, Trophy, CalendarDays, ShieldCheck, LockKeyhole, Menu, X, Gamepad2, Copy, Check, UserRoundCheck, Bell, Eye, Trash2, ShoppingBag} from 'lucide-react';
import './styles.css';
import './parent.css';

type Video={id:string;title:string;category:string;description:string};
const CHANNEL='https://www.youtube.com/@iAmSupremeYT/videos';
const videos:Video[]=[
 {id:'lbRWG5zpYMg',title:'I BECAME A YN JANITOR IN ROBLOX FIGHT IN A SCHOOL',category:'Roblox Takeovers',description:'Supreme takes over Fight in a School with a wild janitor challenge.'},
 {id:'cNcAwyCozK0',title:'I GOT THE NEW STYLES IN ROBLOX FIGHT IN A SCHOOL',category:'Roblox Takeovers',description:'New styles, new moves, and another Supreme takeover.'},
 {id:'GKUNoXDy37E',title:'NEW SHADOW GLOVES TAKEOVER',category:'Challenges',description:'Supreme tests the new Shadow Gloves in Roblox Fight in a School.'},
 {id:'IHm0lb0-4hk',title:'WE BECAME DOORDASHERS IN ROBLOX',category:'Funny Moments',description:'The DoorDash takeover comes to Roblox Fight in a School.'},
 {id:'3BPBdfIy7U0',title:'RED SHOES TAKEOVER',category:'Roblox Takeovers',description:'Supreme takes over with the red shoes.'},
 {id:'kVB4lzZwUlo',title:'PURPLE SHOES TAKEOVER',category:'Challenges',description:'A full purple shoes challenge in Roblox Fight in a School.'}
];
const cats=['All Videos','Roblox Takeovers','Challenges','Funny Moments','Shorts'];

function App(){
 const [page,setPage]=useState<'home'|'watch'|'events'|'rewards'|'merch'|'parent'>('home');
 const [current,setCurrent]=useState(videos[0]); const [cat,setCat]=useState('All Videos'); const [query,setQuery]=useState(''); const [menu,setMenu]=useState(false); const [copied,setCopied]=useState(false);
 const filtered=useMemo(()=>videos.filter(v=>(cat==='All Videos'||v.category===cat)&&v.title.toLowerCase().includes(query.toLowerCase())),[cat,query]);
 const go=(p:typeof page)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})};
 const step=(n:number)=>{const i=videos.findIndex(v=>v.id===current.id);setCurrent(videos[(i+n+videos.length)%videos.length]);};
 const copy=async()=>{await navigator.clipboard.writeText(`https://youtu.be/${current.id}`);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 return <div className="app">
  <header><button className="brand" onClick={()=>go('home')}><span>I AM</span>SUPREME<span>YT</span></button><nav className={menu?'open':''}>
   <button onClick={()=>go('home')}>Home</button><button onClick={()=>go('watch')}>Supreme TV</button><button onClick={()=>go('events')}>Events</button><button onClick={()=>go('rewards')}>Rewards</button><button onClick={()=>go('merch')}>Merch</button><button onClick={()=>go('parent')}>Parent Zone</button><a className="nav-cta" href={CHANNEL} target="_blank">Subscribe</a>
  </nav><button className="menu" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  {page==='home'&&<main>
   <section className="hero"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> THE TAKEOVER IS LIVE</div><h1>WELCOME TO<br/><em>SUPREME WORLD</em></h1><p>The official home of IAMSUPREMEYT. Watch the latest Roblox takeovers, enter gaming events, complete challenges, and level up with the Supreme Squad.</p><div className="actions"><button className="primary" onClick={()=>go('watch')}><Play fill="currentColor"/> Watch Supreme TV</button><a className="secondary" href={CHANNEL} target="_blank"><Video/> Subscribe on YouTube</a></div></div><div className="hero-mark"><div className="s">S</div><span>WATCH • PLAY • COMPETE</span></div></section>
   <section className="section"><div className="section-head"><div><span className="kicker">LATEST DROPS</span><h2>THE TAKEOVER NEVER STOPS</h2></div><button className="text-link" onClick={()=>go('watch')}>View all videos →</button></div><div className="video-grid">{videos.slice(0,3).map(v=><VideoCard key={v.id} v={v} onPlay={()=>{setCurrent(v);go('watch')}}/>)}</div></section>
   <section className="feature-row"><Feature icon={<CalendarDays/>} title="Gaming Events" text="Join moderated Supreme Squad group gaming sessions and community tournaments." cta="See events" onClick={()=>go('events')}/><Feature icon={<Trophy/>} title="Challenges & Rewards" text="Complete weekly missions, earn points, unlock badges, and climb the leaderboard." cta="View rewards" onClick={()=>go('rewards')}/><Feature icon={<ShoppingBag/>} title="Supreme Merch" text="Official IAMSUPREMEYT shirts, hoodies, accessories, and limited drops are coming soon." cta="Preview merch" onClick={()=>go('merch')}/></section>
  </main>}
  {page==='watch'&&<main className="watch-page"><section className="channel-banner"><img src="https://yt3.googleusercontent.com/lj1cX2WyW3soIsAF0aONHS4EwOGve_Op2qye3T8UwdHPM2wGf0PqHylfjlE1M70xGnB725NV=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj" alt="IAMSUPREMEYT official YouTube channel banner"/></section><section className="page-hero"><span className="kicker">INTERNAL VIEWING HUB</span><h1>SUPREME <em>TV</em></h1><p>Watch official IAMSUPREMEYT uploads right here. Every play uses YouTube's official player.</p></section>
   <section className="watch-layout"><div><div className="player"><iframe src={`https://www.youtube-nocookie.com/embed/${current.id}?rel=0`} title={current.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><div className="now-playing"><div><span className="pill">{current.category}</span><h2>{current.title}</h2><p>{current.description}</p></div><div className="player-actions"><button onClick={()=>step(-1)} aria-label="Previous"><ChevronLeft/></button><button onClick={copy}>{copied?<Check/>:<Copy/>}</button><button onClick={()=>navigator.share?.({title:current.title,url:`https://youtu.be/${current.id}`})}><Share2/></button><button onClick={()=>step(1)} aria-label="Next"><ChevronRight/></button></div></div></div>
    <aside><div className="queue-title"><span>UP NEXT</span><b>{videos.length} VIDEOS</b></div>{videos.map((v,i)=><button className={`queue-item ${current.id===v.id?'active':''}`} key={v.id} onClick={()=>setCurrent(v)}><img src={`https://i.ytimg.com/vi/${v.id}/mqdefault.jpg`} alt=""/><span><small>{String(i+1).padStart(2,'0')} • {v.category}</small>{v.title}</span></button>)}</aside></section>
   <section className="library section"><div className="library-tools"><h2>VIDEO LIBRARY</h2><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Supreme TV"/></div></div><div className="tabs">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="video-grid">{filtered.map(v=><VideoCard key={v.id} v={v} onPlay={()=>{setCurrent(v);window.scrollTo({top:0,behavior:'smooth'})}}/>)}</div>{!filtered.length&&<div className="empty">No videos found in this category yet.</div>}<a className="primary channel-button" href={CHANNEL} target="_blank"><Video/> Visit & Subscribe to IAMSUPREMEYT</a></section>
  </main>}
  {page==='events'&&<SimplePage kicker="THE GAMING ARENA" title="PLAY WITH THE SQUAD" icon={<Gamepad2/>} text="Supreme's moderated Roblox events, challenges, and tournament registrations will live here. Guardian approval is required for eligible younger players." button="Join the event waitlist"/>}
  {page==='rewards'&&<SimplePage kicker="LEVEL UP" title="SUPREME REWARDS" icon={<Trophy/>} text="Earn Supreme Points through approved challenges, unlock badges, collect digital rewards, and rise through the Supreme Squad leaderboard." button="Join Supreme Squad"/>}
  {page==='merch'&&<SimplePage kicker="OFFICIAL IAMSUPREMEYT GEAR" title="SUPREME MERCH COMING SOON" icon={<ShoppingBag/>} text="Get ready for official Supreme Squad shirts, hoodies, gaming accessories, limited-edition drops, and digital collectibles. Products are not available for purchase yet." button="Drops coming soon"/>}
  {page==='parent'&&<ParentPage/>}
  <footer><div className="brand"><span>I AM</span>SUPREME<span>YT</span></div><p>Watch. Play. Compete. Join the Takeover.</p><div><a href={CHANNEL} target="_blank">YouTube</a><button onClick={()=>go('parent')}>Parent Information</button><button onClick={()=>go('parent')}>Community Rules</button></div><small>© 2026 IAMSUPREMEYT. YouTube and Roblox are trademarks of their respective owners. This fan hub is not endorsed by Roblox.</small></footer>
 </div>
}
function VideoCard({v,onPlay}:{v:Video;onPlay:()=>void}){return <button className="video-card" onClick={onPlay}><div className="thumb"><img src={`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`} alt=""/><span className="play"><Play fill="currentColor"/></span></div><span className="card-cat">{v.category}</span><h3>{v.title}</h3><p>Watch on Supreme TV →</p></button>}
function Feature({icon,title,text,cta,onClick}:{icon:React.ReactNode;title:string;text:string;cta:string;onClick:()=>void}){return <article className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p><button onClick={onClick}>{cta} →</button></article>}
function SimplePage({kicker,title,icon,text,button}:{kicker:string;title:string;icon:React.ReactNode;text:string;button:string}){return <main className="simple"><div className="simple-card"><div className="big-icon">{icon}</div><span className="kicker">{kicker}</span><h1>{title}</h1><p>{text}</p><button className="primary">{button}</button><div className="notice"><LockKeyhole/> Interactive features are launching soon with guardian and moderator controls.</div></div></main>}
function ParentPage(){
 const [age,setAge]=useState<'under13'|'13plus'>('13plus'); const [sent,setSent]=useState(false);
 return <main className="parent-page">
  <section className="parent-hero"><div><span className="kicker">PARENT & GUARDIAN CENTER</span><h1>SAFE PLAY.<br/><em>REAL CONTROL.</em></h1><p>Families should always understand what is collected, what children can do, and what requires adult approval.</p></div><ShieldCheck/></section>
  <section className="safety-grid"><article><UserRoundCheck/><h3>Guardian-managed access</h3><p>Fans under 13 cannot use interactive features until a parent or guardian approves their account.</p></article><article><Eye/><h3>Moderated interaction</h3><p>Group events and submitted questions are reviewed. There are no private fan-to-creator messages.</p></article><article><Bell/><h3>Permission notices</h3><p>Guardians receive clear notices for event participation, account changes, and future purchases.</p></article><article><Trash2/><h3>Privacy controls</h3><p>Guardians can request access, correction, download, or deletion of their child's account data.</p></article></section>
  <section className="join-panel"><div className="join-copy"><span className="kicker">JOIN THE SUPREME SQUAD</span><h2>CREATE A SAFE FAN PROFILE</h2><p>We only request information needed to create and protect the account. We never ask for a child's exact birthdate, address, school, phone number, or live location.</p><ul><li>The leaderboard uses a gamer tag—not a real name.</li><li>Moderators check every new gamer tag.</li><li>Interactive tools stay locked while guardian consent is pending.</li></ul></div>
   <form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Display name (gamer tag)<small>Shown on the leaderboard. Moderators check every new name.</small><input required minLength={3} maxLength={20} placeholder="Choose a safe gamer tag"/></label><fieldset><legend>Age band</legend><small>We never ask for an exact birthdate.</small><div className="age-options"><label><input type="radio" name="age" checked={age==='under13'} onChange={()=>setAge('under13')}/> Under 13</label><label><input type="radio" name="age" checked={age==='13plus'} onChange={()=>setAge('13plus')}/> 13 or older</label></div></fieldset>{age==='under13'&&<label>Parent or guardian email<small>We email them to confirm consent. Interactive features stay switched off until they approve.</small><input required type="email" placeholder="guardian@example.com"/></label>}<label className="check"><input required type="checkbox"/><span>I have read the <a href="#rules">community rules</a> and the <a href="#privacy">privacy policy</a>.</span></label><button className="primary" type="submit">Request to join</button>{sent&&<div className="success" role="status"><Check/> Request received. {age==='under13'?'Guardian consent is required before interactive features unlock.':'Your profile is waiting for moderator review.'}</div>}</form>
  </section>
  <section className="policy-grid" id="rules"><article><h2>Community Rules</h2><ol><li>Use a safe gamer tag and protect personal information.</li><li>Be respectful—no bullying, threats, hate speech, or inappropriate language.</li><li>Never share passwords, contact information, school, or location.</li><li>Follow moderator instructions during every Supreme event.</li><li>Report anything that feels unsafe or uncomfortable.</li></ol></article><article id="privacy"><h2>Parent Controls</h2><p>Parents and guardians can review permissions, event requests, and account activity; manage notifications; and request account-data access or deletion.</p><p className="legal">This page provides product information and is not legal advice. Final privacy, consent, and terms documents require legal review before public launch.</p></article></section>
 </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
